name: Generate Metrics

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics with Spotify music
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.SPOTIFY_TOKENS }}
          base: ""
          config_timezone: America/New_York
          config_display: columns

          # Recently played
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_mode: recent
          plugin_music_limit: 5
          plugin_music_played_at: yes

          # Top artists
          plugin_music_top_type: artists
          plugin_music_time_range: long
