name: Generate Metrics

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Top Artists
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_timezone: America/New_York
          # config_display: columns

          plugin_music: yes
          plugin_music_mode: top
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_time_range: long
          plugin_music_limit: 5
          plugin_music_top_type: artists
